language: "zh"

pipeline:
  - name: SpacyNLP
    model: "zh_core_web_sm"
    case_sensitive: TRUE
    intent_tokenization_flag: True
    intent_split_symbol: "_"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7


policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 3
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.7
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True

assistant_id: 20240718-142606-kinetic-fencing


