recipe: default.v1
assistant_id: 20230604-204819-obliging-stave
language: zh

pipeline:
- name: JiebaTokenizer
  token_pattern: (?u)\b\w+\b
  dictionary_path: "data/"
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  ranking_length: 5
- name: EntitySynonymMapper
- name: RegexEntityExtractor
  use_word_boundaries: false
  use_lookup_tables: true
  use_regexes: true
- name: ResponseSelector
  epochs: 100
  retrieval_intent: faq
- name: FallbackClassifier
  threshold: 0.7
policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- max_history: 6
  name: AugmentedMemoizationPolicy
- name: TEDPolicy
  max_history: 10
  epochs: 40
  batch_size:
  - 32
  - 64