version: "3.1"

nlu:
- intent: greet
  examples: |
    - hello
    - hi
    - 你好
- intent: goodbye
  examples: |
    - 再见
    - 拜拜
    - bye
- intent: faq/how_to_leave
  examples: |
    - 怎么请假
    - 如何请假
    - 我想请个假该怎么做
    - 请假需要做什么
- intent: faq/leave_type
  examples: |
    - 有哪些请假类型
    - 我可以请哪些假
    - 支持的请假类型有哪些
- intent: faq/leave_flow
  examples: |
    - 怎么查看请假审批进程
    - 请假进度
    - 请假审批进度
    - 在哪看请假进度
- intent: leave
  examples: |
    - 帮我请个假
    - 我想请[一天](duration)假
    - 帮我请[一周](duration)假
    - 我要请[三天](duration)假
    - [今天](begin_time)我要请[一天](duration)假
    - [10月9号](begin_time)我要请[一天](duration)假
    - 我需要请[半天](duration)[事假](leave_type)
    - 帮我请[1天](duration)[病假](leave_type)
    - [后天](begin_time)我想请[一天](duration)[年假](leave_type)
    - 从[明天](begin_time)开始请[2天](duration)[年假](leave_type)
    - [6月1号](begin_time)帮我请[一天](duration)[调休假](leave_type)
- intent: info_begin_time
  examples: |
    - [今天](begin_time)
    - [明天](begin_time)
    - [后天](begin_time)
    - [6月10号](begin_time)
    - [3月2号](begin_time)
    - [7月1号](begin_time)
    - [3月3日](begin_time)
    - [12月25日](begin_time)
- intent: info_duration
  examples: |
    - [1天](duration)
    - [一天](duration)
    - [两天](duration)
    - [三天](duration)
    - [半天](duration)
    - [一周](duration)
- intent: info_leave_type
  examples: |
    - [事假](leave_type)
    - [病假](leave_type)
    - [婚假](leave_type)
- lookup: leave_type
  examples: |
    - 事假
    - 病假
    - 年假
    - 婚假
    - 调休假
    - 育儿假
    - 呱呱假
- synonym: "0.5"
  examples: |
    - 半天
- synonym: "1"
  examples: |
    - 1天
    - 一天
- synonym: "2"
  examples: |
    - 两天
    - 二天
- synonym: "3"
  examples: |
    - 三天
    - 3天
- synonym: "7"
  examples: |
    - 七天
    - 一周